FROM node:20.11.1-alpine3.19

RUN apk add build-base git krb5-dev libgit2-dev libssh-dev pkgconfig python3 tzdata

# Ensure C++17 is used explicitly for Node.js 20
ENV CXXFLAGS="-std=c++17"
ENV CFLAGS="-std=c17"

ADD . /app
WORKDIR /app

RUN npm ci && \
  npx prebuildify --napi --strip --tag-libc -t "$(node --version | tr -d 'v')"
