on:
  push:
    branches:
      - master
      - backport/*
    tags:
      - v*.*.*
  pull_request:

jobs:
  linux-test:
    name: "test node ${{ matrix.node-version }} on linux"
    env:
      CC: clang
      CXX: clang++
      npm_config_clang: 1
      GYP_DEFINES: use_obsolete_asm=true
      DEBIAN_FRONTEND: "noninteractive"
    runs-on: ubuntu-22.04
    container: ubuntu:22.04
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: prerequisites
        run: |
          apt-get update
          apt-get install -y software-properties-common git build-essential clang libssl-dev libkrb5-dev libc++-dev wget python3 zlib1g-dev
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

  mac-test:
    name: "test node ${{ matrix.node-version }} on macOS"
    env:
      CC: clang
      CXX: clang++
      npm_config_clang: 1
      GYP_DEFINES: use_obsolete_asm=true
    runs-on: macos-26
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

  linux-arm-test:
    name: "test node ${{ matrix.node-version }} on linux-arm"
    env:
      CC: clang
      CXX: clang++
      npm_config_clang: 1
      GYP_DEFINES: use_obsolete_asm=true
      CXXFLAGS: -std=c++17
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common git build-essential clang libssl-dev libkrb5-dev libc++-dev wget python3 zlib1g-dev
