on:
  push:
    branches:
      - master
      - backport/*
    tags:
      - v*.*.*
  pull_request:

jobs:
  linux-test:
    name: "test on linux"
    env:
      CC: clang
      CXX: clang++
      npm_config_clang: 1
      GYP_DEFINES: use_obsolete_asm=true
      DEBIAN_FRONTEND: "noninteractive"
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
      - name: prerequisites
        run: |
          apt-get update
          apt-get install -y software-properties-common git build-essential clang libssl-dev libkrb5-dev libc++-dev wget python3
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Test
        run: |
          set -xe
          mkdir ~/.ssh_tests
          chmod 700 ~/.ssh_tests
          printf "%b" "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh_tests/config
          cat test/id_rsa.pub > ~/.ssh_tests/id_rsa.pub
          cat test/id_rsa.enc | base64 -d > ~/.ssh_tests/id_rsa
          ls ~/.ssh_tests
          chmod 600 ~/.ssh_tests/id_rsa*
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh_tests/id_rsa

          npm install
          npm test

  mac-test:
    name: "macOS tests"
    env:
      CC: clang
      CXX: clang++
      npm_config_clang: 1
      GYP_DEFINES: use_obsolete_asm=true
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Test
        run: |
          set -xe
          mkdir ~/.ssh_tests
          chmod 700 ~/.ssh_tests
          printf "%b" "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh_tests/config
          cat test/id_rsa.pub > ~/.ssh_tests/id_rsa.pub
          cat test/id_rsa.enc | base64 -d > ~/.ssh_tests/id_rsa
          chmod 600 ~/.ssh_tests/id_rsa*
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh_tests/id_rsa

          npm install
          npm test
